import axios from 'axios';
import FormData from 'form-data';
import { Settings, BugReport, JiraTicket } from '../types/index';

function getAuthHeader(settings: Settings): string {
  const credentials = `${settings.jiraEmail}:${settings.jiraApiKey}`;
  return `Basic ${Buffer.from(credentials).toString('base64')}`;
}

function buildJiraDescription(bugReport: BugReport): object {
  // Build numbered steps as plain paragraphs (bulletList can cause ADF validation failures)
  const stepParagraphs = bugReport.stepsToReproduce.map((step, i) => ({
    type: 'paragraph',
    content: [{ type: 'text', text: `${i + 1}. ${step}` }],
  }));

  const nodes: object[] = [
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'BUG DESCRIPTION', marks: [{ type: 'strong' }] },
      ],
    },
    {
      type: 'paragraph',
      content: [{ type: 'text', text: bugReport.actualResult }],
    },
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'STEPS TO REPRODUCE', marks: [{ type: 'strong' }] },
      ],
    },
    ...stepParagraphs,
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'EXPECTED RESULT', marks: [{ type: 'strong' }] },
      ],
    },
    {
      type: 'paragraph',
      content: [{ type: 'text', text: bugReport.expectedResult }],
    },
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'ACTUAL RESULT', marks: [{ type: 'strong' }] },
      ],
    },
    {
      type: 'paragraph',
      content: [{ type: 'text', text: bugReport.actualResult }],
    },
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'SEVERITY', marks: [{ type: 'strong' }] },
        { type: 'text', text: `  ${bugReport.severity}` },
      ],
    },
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'ENVIRONMENT', marks: [{ type: 'strong' }] },
        { type: 'text', text: `  ${bugReport.environment}` },
      ],
    },
  ];

  if (bugReport.additionalNotes) {
    nodes.push({
      type: 'paragraph',
      content: [
        { type: 'text', text: 'ADDITIONAL NOTES', marks: [{ type: 'strong' }] },
      ],
    });
    nodes.push({
      type: 'paragraph',
      content: [{ type: 'text', text: bugReport.additionalNotes }],
    });
  }

  nodes.push({
    type: 'paragraph',
    content: [
      {
        type: 'text',
        text: 'This ticket was automatically generated by Bug Report Enhancer using Groq LLaMA Scout AI.',
        marks: [{ type: 'em' }],
      },
    ],
  });

  return { type: 'doc', version: 1, content: nodes };
}

export async function createJiraTicket(
  bugReport: BugReport,
  settings: Settings,
  customFields?: Record<string, unknown>
): Promise<JiraTicket> {
  const jiraBaseUrl = settings.jiraUrl.replace(/\/$/, '');
  const authHeader = getAuthHeader(settings);
  const commonHeaders = {
    Authorization: authHeader,
    'Content-Type': 'application/json',
    Accept: 'application/json',
  };

  // Step 1: Fetch the project's valid issue types so we don't hardcode a name
  const projectRes = await axios.get(`${jiraBaseUrl}/rest/api/3/project/${settings.jiraProjectKey}`, {
    headers: commonHeaders,
  });
  const issueTypes: Array<{ name: string; id: string }> = projectRes.data.issueTypes || [];
  const preferredName = (settings.jiraIssueType || 'Bug').toLowerCase();

  const matched =
    issueTypes.find(t => t.name.toLowerCase() === preferredName) ||
    issueTypes.find(t => t.name.toLowerCase().includes(preferredName)) ||
    issueTypes.find(t => !t.name.toLowerCase().includes('subtask')) ||
    issueTypes[0];

  if (!matched) {
    throw new Error(`No usable issue types found in project ${settings.jiraProjectKey}.`);
  }

  console.log(`[CreateTicket] Using issue type: "${matched.name}" (requested: "${settings.jiraIssueType}")`);

  // Step 2: Build the issue payload with standard + custom fields
  const fields: Record<string, unknown> = {
    project: { key: settings.jiraProjectKey },
    summary: bugReport.title,
    description: buildJiraDescription(bugReport),
    issuetype: { name: matched.name },
  };

  // Merge custom fields into the payload
  if (customFields && Object.keys(customFields).length > 0) {
    console.log(`[CreateTicket] Adding ${Object.keys(customFields).length} custom field(s):`);
    for (const [fieldId, value] of Object.entries(customFields)) {
      console.log(`  ${fieldId}: ${JSON.stringify(value)}`);
      fields[fieldId] = value;
    }
  }

  const issuePayload = { fields };

  let response;
  try {
    response = await axios.post(`${jiraBaseUrl}/rest/api/3/issue`, issuePayload, { headers: commonHeaders });
  } catch (err: unknown) {
    const axiosErr = err as { response?: { status?: number; data?: unknown }; message?: string };
    console.error('[CreateTicket] Jira API error status:', axiosErr.response?.status);
    console.error('[CreateTicket] Jira API error body:', JSON.stringify(axiosErr.response?.data, null, 2));
    throw err;
  }

  const issueKey = response.data.key as string;
  const issueId = response.data.id as string;
  const issueUrl = `${jiraBaseUrl}/browse/${issueKey}`;

  return { issueKey, issueId, issueUrl, summary: bugReport.title };
}

export async function attachFilesToTicket(
  issueKey: string,
  files: Express.Multer.File[],
  settings: Settings
): Promise<Array<{ filename: string; size: number; success: boolean; error?: string }>> {
  const jiraBaseUrl = settings.jiraUrl.replace(/\/$/, '');
  const authHeader = getAuthHeader(settings);
  const results: Array<{ filename: string; size: number; success: boolean; error?: string }> = [];

  for (const file of files) {
    try {
      const form = new FormData();
      form.append('file', file.buffer, {
        filename: file.originalname,
        contentType: file.mimetype,
        knownLength: file.size,
      });

      await axios.post(
        `${jiraBaseUrl}/rest/api/3/issue/${issueKey}/attachments`,
        form,
        {
          headers: {
            ...form.getHeaders(),
            Authorization: authHeader,
            'X-Atlassian-Token': 'no-check', // Required by Jira to allow attachments
          },
          maxBodyLength: Infinity,
          maxContentLength: Infinity,
        }
      );

      console.log(`[Attach] Attached: ${file.originalname} (${file.size} bytes)`);
      results.push({ filename: file.originalname, size: file.size, success: true });
    } catch (err: unknown) {
      const axiosErr = err as { message?: string; response?: { data?: unknown } };
      console.error(`[Attach] Failed to attach ${file.originalname}:`, axiosErr.response?.data || axiosErr.message);
      results.push({ filename: file.originalname, size: file.size, success: false, error: axiosErr.message });
    }
  }

  return results;
}

export async function testJiraConnection(settings: Settings): Promise<{ success: boolean; userIdentifier?: string }> {
  const jiraBaseUrl = settings.jiraUrl.replace(/\/$/, '');
  const authHeader = getAuthHeader(settings);

  const response = await axios.get(`${jiraBaseUrl}/rest/api/3/myself`, {
    headers: {
      Authorization: authHeader,
      Accept: 'application/json',
    },
  });

  // displayName is always present; emailAddress may be hidden by Jira privacy settings
  const userIdentifier: string =
    response.data.displayName ||
    response.data.emailAddress ||
    response.data.accountId ||
    'Unknown user';

  return {
    success: true,
    userIdentifier,
  };
}
